[battery]
governor = "powersave"
turbo = "auto"
enable_auto_turbo = true
turbo_auto_settings = { load_threshold_high = 80.0, load_threshold_low = 40.0, temp_threshold_high = 70.0, initial_turbo_state = false }
epp = "power"
epb = "power"
platform_profile = "low-power"
min_freq_mhz = 2000
max_freq_mhz = 4800

[charger]
governor = "performance"
turbo = "auto"
enable_auto_turbo = true
turbo_auto_settings = { load_threshold_high = 70.0, load_threshold_low = 30.0, temp_threshold_high = 75.0, initial_turbo_state = true }
epp = "performance"
epb = "performance"
platform_profile = "performance"
min_freq_mhz = 2000
max_freq_mhz = 4800

[daemon]
# Base polling interval in seconds
poll_interval_sec = 5
# Enable adaptive polling that changes with system state
adaptive_interval = true
# Minimum polling interval for adaptive polling (seconds)
min_poll_interval_sec = 1
# Maximum polling interval for adaptive polling (seconds)
max_poll_interval_sec = 10
# Double the polling interval when on battery to save power
throttle_on_battery = true
# Logging level: Error, Warning, Info, Debug
log_level = "Info"
